package world;

public enum TileType 
{
	NULL_TILE, DIRT_TILE, GRASS_TILE, WATER_TILE, 
	
	VERTICAL_WALL_TILE, HORIZONTAL_WALL_TILE,
	
	BOTTOM_RIGHT_WALL, BOTTOM_LEFT_WALL, TOP_RIGHT_WALL, TOP_LEFT_WALL,
	
	RIGHT_HILL_FACE, BOTTOM_HILL_FACE,
	
	WOOD_TILE
}
