package main;

public enum Mode 
{
	NO_MODE, COLLISION_BOX, DATA_MODE,
	
	MAIN_DISPLAY, MENU_DISPLAY, HELP_DISPLAY, SHOP_DISPLAY, PAUSE_DISPLAY,
	
	STANDARD, EXPLOSIVE, SCATTER, FIRE,
	
	SAVE, SAVE_GAME_ONE, SAVE_GAME_TWO, SAVE_GAME_THREE,
	
	LOAD, LOAD_GAME_ONE, LOAD_GAME_TWO, LOAD_GAME_THREE
}
